### ISSUE TITLE
Doesn't exist in GDS connectors

### ISSUE THREAD

**Issue by justin-vanwinkle** [george-dilthey/ynab-gds-connector#1]
This is fantastic! Thanks for sharing it!

I am looking to implement it, but it appears to not be published in GDS anymore. When I search for it in the data sources, it doesn't come up. Have they removed it?

Thanks!

**Comment by justin-vanwinkle** [comment]
More info on this... I cloned your report and started authorizing. And got this message:

Google hasn’t verified this app
The app is requesting access to sensitive info in your Google Account. Until the developer (george.dilthey@gmail.com) verifies this app with Google, you shouldn't use it.

That explains why I can't see the connector in GDS :)

**Comment by george-dilthey** [comment]
Hey Justin! Sorry for the confusion. I'm still working on getting this up and running with Google and YNAB! I'll let you know when its finally published.

-George

**Comment by justin-vanwinkle** [comment]
Thanks George! Let me know if I can assist in any way. I cloned what you had and published an Apps Script to use for my personal dashboard. Happy to help!
