### ISSUE TITLE
This look very nice...But I don't see the connector in Google Data Studio

### ISSUE THREAD

**Issue by masey7** [george-dilthey/ynab-gds-connector#2]
This look very nice...But I don't see the connector in Google Data Studio.

Is your connector restricted to USA ? I live in Canada.

See Screenshot for more information.
You may notice that label is in French (French is big in the Quebec province of Canada)

![image](https://user-images.githubusercontent.com/3464889/106387092-169c6000-63a6-11eb-8faf-bc9d5d887ab3.png)

**Comment by george-dilthey** [comment]
Hey @masey7! Thanks for taking a look! I'm still in the process of getting this approved by YNAB and GDS. I'll let you know when it goes live!
