### ISSUE TITLE
App Disappeared

### ISSUE THREAD

**Issue by gitlcr2131** [george-dilthey/ynab-gds-connector#3]
Hi.  Your app disappeared so I forked it for personal use.

**Comment by epfreezer33** [comment]
Not finding it in the connector store.

**Comment by tekgy** [comment]
@george-dilthey Insights for YNAB is still missing from GDS connector search. @gitlcr2131 I tried to follow your lead but can't seem to get it to let me authenticate. Did it work out of the box for you? I'll have to try again another time.

**Comment by george-dilthey** [comment]
Hey! Sorry. This was a small project that I never got to finish. You May be able to fork it down but I'm not 100% sure. I'll see if I can work on it again to get it live.

**Comment by tekgy** [comment]
Thanks so much for the reply!

It’d be awesome to get it working again if it’s easy and quick! If you
don’t have time, I’ll try to fork it and go through the connector tutorial
a bit more carefully to see how I might fix it up!

I saw a YNAB dev or support person recommend Insights to a user in the
forum today, and it’s still listed on the Works with YNAB page, so you
might get more people wondering what happened.

Cheers!
Chris

**Comment by george-dilthey** [comment]
Ya I built it originally as a learning project. I'm going through a coding bootcamp now so I'll probably want to revisit it again to see what I can improve and polish. I'll let ya know when I have time to get to it. Feel free to ping if you have any questions while you're going through. I may be able to help.

**Comment by george-dilthey** [comment]
@tekgy @epfreezer33 @gitlcr2131 I've updated the Readme with a direct link which should let you access the connector. I'm still working on getting it published to the gallery. Would love any feedback if you all use it!

https://datastudio.google.com/u/0/datasources/create?connectorId=AKfycbyexS2r_aeNSAA--7lEF3iaV_sjjQMgfTwMnuaLYVj-Io-63jdGoCmuW2MvY4Gf7vIXOw

**Comment by zgosalvez** [comment]
I've alternatively used https://www.kajiba.io/docs/sheets-for-ynab/, then use the Google Sheets connector.

@george-dilthey, thanks for sharing the connector but I find it slow with my thousands of transactions so using Google Sheets to precache the data makes my reports load faster.

**Comment by george-dilthey** [comment]
Makes sense, thanks for the feedback. There may be ways to optimize it so I'll look into that.

**Comment by zgosalvez** [comment]
Additionally, querying Google Sheets is faster since it uses BigQuery BI engine.  For anyone who thinks loading the data source takes a long while, consider extracting the data which also uses the BigQuery BI engine. https://support.google.com/datastudio/answer/9019969
